#!/bin/bash -

INTERFACE=eth1
ROOTDIR=/root/pcap/
PREFIX=

# wait for the time to get set
while [ `date +%Y` == "1969" ]
do
	echo "Waiting for correct time"
	sleep 1
done

/usr/bin/tcpdump -i $INTERFACE -U -w $ROOTDIR$PREFIX`date +%Y%m%d%H%M%S`.pcap tcp and port 22222
