#!/bin/bash -

DBHOST=192.168.1.13

# wait for the time to get set
while [ `date +%Y` == "1969" ]
do
	echo "Waiting for correct time"
	sleep 1
done

cd /root
#/usr/bin/python /root/solaredge/seconvert.py -v -f -d solar -h $DBHOST pcap/
#/usr/bin/python /root/solaredge/seconvert1.py -f -v pcap/ | python /root/solaredge/seconvert2.py -v -j /root/solar.json -d solar -h $DBHOST
/usr/bin/python /root/solaredge/seconvert1.py -f -v pcap/ | python /root/solaredge/seconvert2.py -v -j /root/solar.json

