#!/bin/bash -

INTERFACE=eth1
ROOTDIR=/root/data/
PREFIX=

# wait for the time to get set
while [ `date +%Y` == "1969" ]
do
	echo "Waiting for correct time"
	sleep 1
done

python /root/solaredge/semonitor.py -vv -n $INTERFACE -j stdout | tee $ROOTDIR$PREFIX`date +%Y%m%d%H%M%S`.json | python /root/solaredge/sestate.py -o /root/solar.json
