version: 2.1
commands:
  setup_and_test:
    steps:
      - run: 
          command: |
            curl -sSL https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install -y git-lfs tshark xxd
      - checkout
      - restore_cache:
          key: v1-requirements-{{ checksum "/usr/local/bin/python" }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: v1-requirements-{{ checksum "/usr/local/bin/python" }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            test/test.sh
jobs:
  "Python 2":
    docker:
      - image: circleci/python:2.7
    steps:
      - setup_and_test
  "Python 3":
    docker:
      - image: circleci/python:3.7
    steps:
      - setup_and_test

workflows:
  test:
    jobs:
      - "Python 2"
      - "Python 3"
