#!/bin/bash -

INTERFACE=eth1
PCAPDIR=/data/pcap/
PREFIX=

# wait for the time to get set
while [ `date +%Y` == "1969" ]
do
	echo "Waiting for correct time"
	sleep 1
done

/usr/bin/tcpdump -i ${INTERFACE} -U -w ${PCAPDIR}${PREFIX}`date +%Y%m%d%H%M%S`.pcap tcp
