#!/bin/bash -

INTERFACE=eth1
DATADIR=/data/data/
STATEDIR=/root/
PREFIX=

# wait for the time to get set
while [ `date +%Y` == "1969" ]
do
	echo "Waiting for correct time"
	sleep 1
done

python /root/solaredge/semonitor.py -vv -n ${INTERFACE} | tee ${DATADIR}${PREFIX}`date +%Y%m%d%H%M%S`.json | python /root/solaredge/se2state.py -o ${STATEDIR}solar.json
