#!/bin/bash -

DATADIR=/root/solaredge/data/
STATEDIR=/root/solaredge/state/
PREFIX=
INVERTERS=730A8690,7F104A16

# wait for the time to get set
while [ `date +%Y` == "1969" ]
do
	echo "Waiting for correct time"
	sleep 1
done

python /root/solaredge/semonitor.py -vv -t n -p 22222,22221| \
stdbuf -oL uniq | \
tee ${DATADIR}${PREFIX}`date +%Y%m%d%H%M%S`.json | \
python /root/solaredge/conversion/se2state.py -i ${INVERTERS} -o ${STATEDIR}solar.json
